package by.epamtc.protsko.rentcar.controller.command;

public enum ParameterName {
	GO_TO_MAIN_PAGE,
	SAVE_NEW_USER,
	AUTHENTICATION,
	REGISTRATION,
	GO_TO_SHOW_USER_PROFILE_PAGE,
	CHECK_USER_AUTH_DATA,
	CHANGE_LOCALE,
	GO_TO_EDIT_USER_DATA_PAGE,
	EDIT_USER_DATA,
	SIGN_OUT,
	GET_ALL_USERS,
	FIND_USER,
	GO_TO_FIND_USER_PAGE,
	DELETE_USER,
	GO_TO_CONTACT_PAGE,
	GO_TO_OUR_CARS_PAGE,
	GET_CARS,
	SHOW_ALL_USER_DATA,
	GO_TO_CAR_PAGE

}
