package by.epamtc.protsko.rentcar.controller.command;

public enum ParameterName {
	GO_TO_MAIN_PAGE,
	SAVE_NEW_USER,
	AUTHENTICATION,
	REGISTRATION,
	GO_TO_USER_PROFILE,
	CHECK_AUTH_DATA,
	CHANGE_LOCALE,
	GO_TO_EDIT_PROFILE_PAGE,
	EDIT_PROFILE,
	SIGN_OUT,
	FIND_USER,
	GO_TO_USER_MANAGEMENT_PAGE,
	DELETE_USER,
	GO_TO_CONTACT_PAGE,
	GO_TO_OUR_CARS_PAGE,
	GET_CARS,
	GO_TO_CAR_PAGE,
	CREATE_ORDER
}
