package by.epamtc.protsko.rentcar.controller.command;

public enum ParameterName {
	GO_TO_MAIN_PAGE,
	SAVE_NEW_USER,
	WELCOME_NEW_USER,
	AUTHENTICATION,
	REGISTRATION,
	SHOW_USER_REG_DATA,
	CHECK_USER_AUTH_DATA,
	CHANGE_LOCALE,
	GO_TO_EDIT_USER_DATA_PAGE,
	EDIT_USER_DATA,
	SIGN_OUT,
	GET_ALL_USERS,
	FIND_USER,
	GO_TO_FIND_USER_PAGE
}
